name: Generate Datas
on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Generate Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: FadiBrahem
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Configure Git and Commit Changes
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit Changes
        run: |
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update snake animation"

      # Push to Output Branch using snaketoken
      - name: Push Changes
        env:
          TOKEN: ${{ secrets.snaketoken }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/FadiBrahem/FadiBrahem.git
          git push origin output
